# Generated by Django 3.2 on 2021-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HS6Label',
            fields=[
                ('labels', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20000)),
            ],
            options={
                'db_table': 'HS6_label',
                'managed': True,
            },
        ),
    ]
